project/models.py
from .database import Base
from flask_security import UserMixin, RoleMixin
from sqlalchemy import create_engine
from sqlalchemy.orm import relationship, backref
from sqlalchemy import Boolean, DateTime, Column, Integer, \
                    String, ForeignKey, UnicodeText

class RolesUsers(Base):
    __tablename__ = 'roles_users'
    id = Column(Integer(), primary_key=True)
    user_id = Column('user_id', Integer(), ForeignKey('user.id'))
    role_id = Column('role_id', Integer(), ForeignKey('role.id'))

class Role(Base, RoleMixin):
    __tablename__ = 'role'
    id = Column(Integer(), primary_key=True)
    name = Column(String(80), unique=True)
    description = Column(String(255))
    permissions = Column(UnicodeText)

class User(Base, UserMixin):
    __tablename__ = 'user'
    id = Column(Integer, primary_key=True)
    email = Column(String(255), unique=True)
    username = Column(String(255), unique=True, nullable=True)
    password = Column(String(255), nullable=False)
    last_login_at = Column(DateTime())
    current_login_at = Column(DateTime())
    last_login_ip = Column(String(100))
    current_login_ip = Column(String(100))
    login_count = Column(Integer)
    active = Column(Boolean())
    fs_uniquifier = Column(String(255), unique=True, nullable=False)
    confirmed_at = Column(DateTime())
    roles = relationship('Role', secondary='roles_users',
                         backref=backref('users', lazy='dynamic'))

project/app.py
import os
import sys
import string
import random
import uuid

from flask import Flask, session, render_template_string, render_template, redirect, url_for, flash, request, current_app
from flask_security import Security, current_user, auth_required, hash_password, SQLAlchemySessionUserDatastore
from flask_login import login_user, logout_user
from flask_font_awesome import FontAwesome

from flask_dance.contrib.google import make_google_blueprint, google
from urllib.parse import urlencode

from flask_mailman import Mail
from werkzeug.middleware.proxy_fix import ProxyFix
from werkzeug.security import generate_password_hash

from .config import Config, ProductionConfig, DevelopmentConfig
from dotenv import load_dotenv

from .database import db_session, init_db
from .models import User, Role

from .views import views_bp

fa = FontAwesome()

# Create app
def create_app():
    app = Flask(__name__, instance_relative_config=True)
    app.config['MAX_CONTENT_LENGTH'] = 20 * 1024 * 1024  # Set the maximum allowed request size to 100MB
    debug_mode = False
    print("Creating app")
    for i, arg in enumerate(sys.argv):
        print("arg: " + str(arg))
        if arg == "--debug":
            print("debug mode activé")
            app.config.from_object(DevelopmentConfig)
            debug_mode = True        
            break
    print("end of variable retrieval")

    if not debug_mode:
        app.config.from_object(ProductionConfig)
        # Create Google OAuth blueprint
        google_blueprint = make_google_blueprint(
            client_id=app.config['GOOGLE_OAUTH_CLIENT_ID'],
            client_secret=app.config['GOOGLE_OAUTH_CLIENT_SECRET'],
            scope=["https://www.googleapis.com/auth/userinfo.email", "openid"],
            redirect_url="/authorized",
        )
        # Register the Google OAuth blueprint
        app.register_blueprint(google_blueprint, url_prefix="/login")

        def google_login_url():
            google_auth_url = url_for("google.login", _external=True)
            params = {
                "access_type": "offline",
                "prompt": "consent",
            }
            return f"{google_auth_url}?{urlencode(params)}"

        @app.context_processor
        def inject_google_login_url():
            return dict(google_login_url=google_login_url)

    user_datastore = SQLAlchemySessionUserDatastore(db_session, User, Role)
    print("user_datastore retrieved in prod")
    app.security = Security(app, user_datastore)
    print("app.security initialized in prod")

    mail = Mail(app)

    app.wsgi_app = ProxyFix(
        app.wsgi_app, x_for=1, x_proto=1, x_host=1, x_prefix=1
    )

    @app.route('/authorized')
    def authorized():
        if debug_mode:
            return "Not available in development mode", 404
        if not google.authorized:
            return redirect(url_for("google.login"))
        resp = google.get("/oauth2/v3/tokeninfo")
        if not resp.ok:
            flash("Failed to authenticate with Google.", "danger")
            return redirect(url_for("views.home"))

        idinfo = resp.json()
        email = idinfo['email']
        if 'name' in idinfo:
            name = idinfo['name']
        else:
            name = email

        # Check if the user's email is in the allowed list
        if email not in app.config['ALLOWED_USERS']:
            flash("Your email is not authorized.", "danger")
            return redirect(url_for("views.home"))

        # Check if the user exists in the database
        user = app.security.datastore.find_user(email=email)
        # If the user does not exist, create a new user
        if not user:
            random_password = generate_random_password()
            hashed_password = generate_password_hash(random_password, method='sha256')
            #fs_uniquifier = str(uuid.uuid4())
            user = app.security.datastore.create_user(email=email, username=name, password=hashed_password)
            db_session.commit()
            
        login_user(user)

        # Set the session variable
        session['logged_in_with_google'] = True

        # Redirect to the desired page after login, e.g., the index page
        return redirect(url_for("views.home"))

    # Register the Google authorized route only in production
    app.add_url_rule('/authorized', view_func=authorized)


    def generate_random_password(length=12):
        characters = string.ascii_letters + string.digits + string.punctuation
        return ''.join(random.choice(characters) for i in range(length))

    @app.route("/logout")
    @auth_required()
    def logout():
        logout_user()
        return redirect(url_for("views.home"))        

    app.register_blueprint(views_bp)

    with app.app_context():
        # Create a user to test with
        init_db()
        for user in app.config['ALLOWED_USERS']:
            if not (user.endswith("gmail.com") or user.endswith("thargo.io")) and not app.security.datastore.find_user(email=user):
                app.security.datastore.create_user(email=user, password=hash_password(generate_random_password()))
        db_session.commit()

        #from admin import admin
        #admin.init_app(app)

        fa.init_app(app)

    return app

app = create_app()

if __name__ == "__main__":
    app.run()

project/views.py
# Views

from flask import Blueprint, render_template, redirect, url_for
from flask_security import current_user, auth_required

from .models import User, Role
from .database import db_session

views_bp = Blueprint('views', __name__)

@views_bp.route('/')
def home():
    return render_template('index.html')


@views_bp.route('/profile')
@auth_required()
def profile():
    if not current_user.is_authenticated:
        return redirect(url_for('security.login'))
    else:
        return render_template('profile.html', name=current_user.email)

''' @app.route('/users', endpoint='users', methods=['GET', 'POST'])
@auth_required
def users():
    form = CreateUserForm()
    if form.validate_on_submit():
        user = User(email=form.email.data, password=form.password.data)
        db.session.add(user)
        db.session.commit()
        flash('User created successfully!', 'success')
        return redirect(url_for('users'))

    users = User.query.all()

    return render_template('users.html', users=users, form=form) '''

project/templates/base.html
{% extends "security/base.html" %}
{% block metas %}
<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="description" content="">
<meta name="author" content="">
{% endblock %}

{%- block head_scripts %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.9.4/css/bulma.css" integrity="sha512-SI0aF82pT58nyOjCNfyeE2Y5/KHId8cLIX/1VYzdjTRs0HPNswsJR+aLQYSWpb88GDJieAgR4g1XWZvUROQv1A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
{%- endblock head_scripts %}


{%- block styles %}
<style>
    .hide { display: none;}
    .fs-center { text-align: center }
    .fs-important { font-size: larger; font-weight: bold }
    .fs-gap { margin-top: 20px; }
    .fs-div { margin: 4px; }
    .fs-error-msg { color: darkred; }
</style>
{%- endblock %}

    {% block body %} 

<section class="hero is-primary is-fullheight">

    <div class="hero-head">
        {% block navbar %} 
        {% include "partials/navbar.html" %}
        {% endblock navbar %} 
    </div>
    <div class="hero-body">
        <div class="container">
            <div class="columns is-centered">
                {% block content -%}
                {%- endblock content %}
            </div>
        </div>
    </div>
    <div class="hero-foot">
        {% block footer -%} 
        {%- endblock footer %}
    </div>
</section>

    {% block scripts %}
    {%- endblock scripts %}

{% endblock body %}

      

project/templates/index.html
{% extends "base.html" %}

{% block content %}
<div class="column is-half">
    <h1 class="title">
      Flask Login Example
    </h1>
    <h2 class="subtitle">
      Easy authentication and authorization in Flask.
    </h2>
</div>
{% endblock %}

project/templates/partials/navbar.html
{% block navbar %}
<nav class="navbar" role="navigation">
    <div class="container">
        <div class="navbar-brand">
            <a class="navbar-item">
                <img src="https://bulma.io/images/bulma-type-white.png" alt="Logo">
              </a>
          <span class="navbar-burger" data-target="navbarMenuHeroA">
            <span></span>
            <span></span>
            <span></span>
          </span>
        </div>
        <div id="navbarMenuHeroA" class="navbar-menu">
            <div class="navbar-end">
                <a href="{{ url_for('views.home') }}" class="navbar-item">
                    Home
                </a>
                {% if current_user.is_authenticated %}
                <a href="{{ url_for('views.profile') }}" class="navbar-item">
                    Profile
                </a>
                
                <a href="{{ url_for('security.logout') }}" class="navbar-item">
                    Logout
                </a>
                {% endif %}
                {% if not current_user.is_authenticated %}
                <a href="{{ url_for('security.login') }}" class="navbar-item">
                    Login
                </a>               
                {% endif %} 
            </div>
        </div>
    </div>
</nav>
{% endblock %}

project/templates/profile.html
{% extends "base.html" %}
{% block content %}
<div class="hero-body">
    <div class="container has-text-centered">
        <h1>Hello {{name}}</h1>
    </div>
</div>
{% endblock %}

project/templates/security/_macros.html
{% macro render_field_with_errors(field) %}
  <div class="field" id="{{ field.id|default('fs-field') }}">
    <div class="control">
      {% set placeholder = field.label.text %}
    {{ field(placeholder=placeholder,**kwargs)|safe }}
    </div>
    {% if field.errors %}
      <ul>
      {% for error in field.errors %}
        <li class="fs-error-msg">{{ error }}</li>
      {% endfor %}
      </ul>
    {% endif %} 
  </div>
{% endmacro %}

{% macro render_field(field) %}
  <div class="fs-div field" id="{{ field.id|default('fs-field') }}">
    {% if field.label.text == "Login" %}
      {{ field(**kwargs)|safe }}
    {% else %} 
    {{ field.label }}    {{ field(**kwargs)|safe }}

    {% endif %}
  </div>
{% endmacro %}

{% macro render_field_errors(field) %}
  <div class="fs-div" id="{{ field.id if field else 'fs-field' }}">
    {% if field and field.errors %}
      <ul>
      {% for error in field.errors %}
        <li class="fs-error-msg">{{ error }}</li>
      {% endfor %}
      </ul>
    {% endif %}
  </div>
{% endmacro %}

{# render WTForms (>3.0) form level errors #}
{% macro render_form_errors(form) %}
  {% if form.form_errors %}
    <div class="fs-div field" id="fs-form-errors">
    <ul>
    {% for error in form.form_errors %}
      <li class="fs-error-msg">{{ error }}</li>
    {% endfor %}
    </ul>
    </div>
  {% endif %}
{% endmacro %}

{% macro prop_next() -%}
  {% if 'next' in request.args %}?next={{ request.args.next|urlencode }}{% endif %}
{%- endmacro %}

project/templates/security/forgot_password.html
{% extends "base.html" %}
{% from "security/_macros.html" import render_field_with_errors, render_field %}

{% block content %}
{% include "security/_messages.html" %}
<h1>{{ _fsdomain('Send password reset instructions') }}</h1>
<form action="{{ url_for_security('forgot_password') }}" method="POST" name="forgot_password_form">
  {{ forgot_password_form.hidden_tag() }}
  {{ render_field_with_errors(forgot_password_form.email) }}
  {{ render_field(forgot_password_form.submit, class="button") }}
</form>
{% endblock %}

project/templates/security/login_user.html
{% extends "base.html" %}
{% from "security/_macros.html" import render_field_with_errors, render_field, render_field_errors, render_form_errors, prop_next %}

{% block content %}
<div class="column is-one-third">
  {% include "security/_messages.html" %}
  <h1 class="title">{{ _fsdomain('Login') }}</h1>
  <div class="block">
    <form action="{{ url_for_security('login') }}{{ prop_next() }}" method="POST" name="login_user_form">
      <div class="box">
        {{ login_user_form.hidden_tag() }}
        {{ render_form_errors(login_user_form) }}
        {% if "email" in identity_attributes %}
          {{ render_field_with_errors(login_user_form.email) }}
        {% endif %}
        {% if login_user_form.username and "username" in identity_attributes %}
          {% if "email" in identity_attributes %}
            <h3>{{ _fsdomain("or") }}</h3>
          {% endif %}
          {{ render_field_with_errors(login_user_form.username) }}
        {% endif %}
      
        {{ render_field_with_errors(login_user_form.password) }}
      </div>
        {{ render_field(login_user_form.remember) }}
        {{ render_field_errors(login_user_form.csrf_token) }}
        {{ render_field(login_user_form.submit, class="button is-rounded is-primary", label="bonjour") }}
    </form>
    {% if security.webauthn %}
      <hr class="fs-gap">
      <h2>{{ _fsdomain("Use WebAuthn to Sign In") }}</h2>
      <div>
        <form method="GET" id="wan-signin-form" name="wan_signin_form">
          <input id="wan_signin" name="wan_signin" type="submit" value="{{ _fsdomain('Sign in with WebAuthn') }}"
            formaction="{{ url_for_security('wan_signin') }}{{ prop_next() }}">
        </form>
      </div>
    {% endif %}
    {% if security.oauthglue %}
      <hr class="fs-gap">
      <h2>{{ _fsdomain("Use Social Oauth to Sign In") }}</h2>
      {% for provider in security.oauthglue.provider_names %}
        <div class="fs-gap">
          <form method="POST" id={{ provider }}-form name={{ provider }}_form>
            <input id={{ provider }} name={{ provider }} type="submit" value="{{ _fsdomain('Sign in with ')~provider }}"
              formaction="{{ url_for_security('oauthstart', name=provider) }}{{ prop_next() }}">
          </form>
        </div>
      {% endfor %}
    {% endif %}
    {% if google_login_url is defined %}
    <a class="button is-rounded is-primary" href="{{ google_login_url() }}" class="button is-primary">
      <span class="icon">
        <i class="fab fa-google"></i>
      </span>
      <span>Sign in with Google</span>
    </a>
    {% endif %}
    {% if security.recoverable %}
    <a class="button is-rounded is-primary" href="{{ url_for_security('forgot_password') }}">{{ _fsdomain('Forgot password') }}</a><br/>
    {% endif %}
  </div>
</div>
{% endblock %}

project/templates/security/register_user.html
{% extends "security/base.html" %}
{% from "security/_macros.html" import render_field_with_errors, render_field, render_form_errors %}

{% block content %}
{% include "security/_messages.html" %}
<h1>{{ _fsdomain('Register') }}</h1>
<form action="{{ url_for_security('register') }}" method="POST" name="register_user_form">
  {{ register_user_form.hidden_tag() }}
  {{ render_form_errors(register_user_form) }}
  {{ render_field_with_errors(register_user_form.email) }}
  {% if security.username_enable %}
    {{ render_field_with_errors(register_user_form.username) }}
  {%  endif %}
  {{ render_field_with_errors(register_user_form.password) }}
  {% if register_user_form.password_confirm %}
    {{ render_field_with_errors(register_user_form.password_confirm) }}
  {% endif %}
  {{ render_field(register_user_form.submit) }}
</form>
{% include "security/_menu.html" %}
{% endblock %}

project/templates/users.html
{% extends "base.html" %}
{% block content %}
<h2>User Management</h2>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    {% for user in users %}
      <tr>
        <td>{{ user.username }}</td>
        <td>{{ user.email }}</td>
        <td>
          <a href="{{ url_for('edit_user', user_id=user.id) }}" class="btn btn-primary btn-sm">Edit</a>
          {% if not user.is_admin %}
            {% if user.is_active %}
              <a href="{{ url_for('block_user', user_id=user.id) }}" class="btn btn-warning btn-sm">Block</a>
            {% else %}
              <a href="{{ url_for('unblock_user', user_id=user.id) }}" class="btn btn-success btn-sm">Unblock</a>
            {% endif %}
            <a href="{{ url_for('delete_user', user_id=user.id) }}" class="btn btn-danger btn-sm">Delete</a>
          {% endif %}
        </td>
      </tr>
    {% endfor %}
  </tbody>
</table>

<div class="row">
  <div class="col-md-6">
    <h3>Create User</h3>
    <form method="POST" action="{{ url_for('create_user') }}">
      {{ form.csrf_token }}
      <div class="form-group">
        <label for="username">Username</label>
        {{ form.username(class="form-control", placeholder="Enter username") }}
      </div>
      <div class="form-group">
        <label for="email">Email</label>
        {{ form.email(class="form-control", placeholder="Enter email address") }}
      </div>
      <div class="form-group">
        <label for="password">Password</label>
        {{ form.password(class="form-control", placeholder="Enter password") }}
      </div>
      <button type="submit" class="btn btn-primary">Create</button>
    </form>
  </div>

  <div class="col-md-6">
    <h3>Change Password</h3>
    <form method="POST" action="{{ url_for('change_password') }}">
      {{ form.csrf_token }}
      <div class="form-group">
        <label for="email">Email</label>
        {{ form.email(class="form-control", placeholder="Enter email address") }}
      </div>
      <div class="form-group">
        <label for="password">New Password</label>
        {{ form.password(class="form-control", placeholder="Enter new password") }}
      </div>
      <button type="submit" class="btn btn-primary">Change</button>
    </form>
  </div>
</div>
{% endblock %}